
import "./globals.css";
import { Montserrat, Noto_Serif } from "next/font/google";
import Sidebar from "./components/Sidebar";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const notoSerif = Noto_Serif({
  subsets: ["latin"],
  variable: "--font-noto-serif",
})

export const metadata = {
  title: "Sample",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${notoSerif.variable} antialiased flex text-black`}>
        <Sidebar/>
        {children}
      </body>
    </html>
  );
}
